server {
    listen 8080;
    server_name localhost;

    location /stub_status {
        stub_status;
        # Allow internal docker networks to access the stub status
        allow 127.0.0.0/8;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
        access_log off;
    }
}
